name: Build
on:
  workflow_call:

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-22.04
    outputs:
      testcases: ${{ steps.enum-tests.outputs.testcases }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate version.json
        shell: bash
        run: make generate
      
      - name: Build images
        uses: docker/build-push-action@v6
        with:
          push: false
          sbom: true
          outputs: type=docker,dest=autograph-images.tar
          context: .

      - uses: actions/upload-artifact@v4
        with:
          name: autograph-images-${{ github.sha }}
          path: autograph-images.tar
