name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-22.04
    outputs:
      testcases: ${{ steps.enum-tests.outputs.testcases }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Build images
        shell: bash
        run: make generate build

      - name: Save images
        shell: bash
        run: |
            mkdir -p docker-cache
            docker save -o docker-cache/autograph-images.tar autograph-app autograph-app-hsm

      - name: Enumerate tests
        id: enum-tests
        shell: bash
        run: |
            echo -n "testcases=" >> $GITHUB_OUTPUT
            yq -o=json '.services | keys' tools/autograph-client/integration-tests.yml | jq -c >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v4
        with:
          name: autograph-images-${{ github.sha }}
          path: docker-cache/
