name: Deploy
on:
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9a-z]+.[0-9a-z]+'

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  dockerhub:
    name: Dockerhub
    runs-on: ubuntu-22.04
    needs:
      - build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: autograph-images-${{ github.sha }}
          run-id: ${{ github.event.workflow_run.id }}
          path: docker-cache/

      - name: Load images
        shell: bash
        run: docker load -i docker-cache/autograph-images.tar

      - name: Push to Dockerhub
        shell: bash
        env:
          GITREF: ${{github.ref}}
          DOCKERHUB_REPO: nkirby/autograph-debug
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker tag autograph-app "${DOCKERHUB_REPO}:${{github.ref_name}}"
            docker push "${DOCKERHUB_REPO}:${{github.ref_name}}"
          elif [[ "$${{github.ref}}" == "refs/heads/main" ]]
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker tag autograph-app ${DOCKERHUB_REPO}:latest
            docker push ${DOCKERHUB_REPO}:latest
          fi
