name: Publish
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Publish to Dockerhub
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: autograph-images-${{ github.sha }}
          run-id: ${{ github.event.workflow_run.id }}
          path: docker-cache/
